services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    restart: unless-stopped

    environment:
      SQLD_NODE: standalone
      SQLD_DB_PATH: /var/lib/sqld/data.db
      SQLD_HTTP_LISTEN_ADDR: 0.0.0.0:8080

    volumes:
      - libsql-data:/var/lib/sqld
    networks:
      - dokploy-network

volumes:
  libsql-data:

networks:
  dokploy-network:
    external: true
