services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - '8080:8080'
      - '5001:5001'
    environment:
      - SQLD_NODE=primary
    volumes:
      - libsql_data:/var/lib/sqld

  postgres:
    image: postgres:18
    platform: linux/amd64
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  libsql_data:
  postgres_data:
