services:
  emdash:
    build: .
    ports:
      - '4321:4321'
    volumes:
      - emdash-data:/app/data
    restart: unless-stopped
    depends_on:
      - libsql

  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - '8080:8080'
      - '5001:5001'
    environment:
      - SQLD_NODE=primary
    volumes:
      - libsql_data:/var/lib/sqld

volumes:
  libsql_data:
  emdash-data:
