services:
  emdash:
    build: .
    ports:
      - '4321:4321'
    volumes:
      - emdash-data:/app/data
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    platform: linux/amd64
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  emdash-data:
  postgres_data:
