// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from 'emdash';

export interface Policy {
	id: string;
	slug: string | null;
	status: string;
	title: string;
	index: number;
	content: PortableTextBlock[];
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
	terms?: Record<string, TaxonomyTerm[]>;
}

export interface Project {
	id: string;
	slug: string | null;
	status: string;
	name: string;
	description: string;
	launch_date: string;
	cover: {
		id: string;
		src?: string;
		alt?: string;
		width?: number;
		height?: number;
		provider?: string;
		previewUrl?: string;
		meta?: Record<string, unknown>;
	};
	createdAt: Date;
	updatedAt: Date;
	publishedAt: Date | null;
	bylines?: ContentBylineCredit[];
	terms?: Record<string, TaxonomyTerm[]>;
}

declare module 'emdash' {
	interface EmDashCollections {
		policies: Policy;
		projects: Project;
	}
}
