nodeVersion: '22.20.0'

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@emdash-cms/admin@0.31.0'
  - '@emdash-cms/auth@0.31.0'
  - '@emdash-cms/blocks@0.31.0'
  - '@emdash-cms/cloudflare@0.31.0'
  - '@emdash-cms/gutenberg-to-portable-text@0.31.0'
  - emdash@0.31.0
